//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WifiRegistration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WifiRegistrationFinalEntities : DbContext
    {
        public WifiRegistrationFinalEntities()
            : base("name=WifiRegistrationFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Complex> Complexes { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<ValidMac> ValidMacs { get; set; }
    }
}
