//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WifiRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unit()
        {
            this.ValidMacs = new HashSet<ValidMac>();
        }
    
        public int Id { get; set; }
        public string UnitNumber { get; set; }
        public string OwnerName { get; set; }
        public string OwnerCell { get; set; }
        public string Memo { get; set; }
        public string ComplexName { get; set; }
    
        public virtual Complex Complex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValidMac> ValidMacs { get; set; }
    }
}
