//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WifiRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidMac
    {
        public int Id { get; set; }
        public string UnitNum { get; set; }
        public string Mac { get; set; }
        public Nullable<System.DateTime> Expire { get; set; }
        public string DeviceType { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
